import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import styleNavbar from "../styles/Navbar.module.css";
import Skills from '../components/skills';
import PersonalInformation from '../components/information';
import Arrow_Down from '../components/icons/icon-arrow';
import Projects from '../components/projects';
import { useState, useEffect, useRef } from "react";

const Home: NextPage = () => {
  const [background, setBgNavbar] = useState("black");
  const [scrollBtn, setScrollBtn] = useState<any>("hidden");
  const init_ref = useRef();
  const ref = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      const main: any = init_ref.current;
      let { y } = main.getBoundingClientRect();

      let bg_color_navbar = y <= 0 ? "#0070f3" : "black";
      let scroll_hidden = y <= 0 ? "visible" : "hidden"; 

      setBgNavbar(bg_color_navbar); 
      setScrollBtn(scroll_hidden);
    }

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    }
  })

  const handleBtnScroll = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header ref={ref} className={styleNavbar.header}>
        <Navbar background={background} ></Navbar> 
      </header>

      <main className={styles.main}>

        <div ref={init_ref} className={styles.main_title}>
          <h1 className={styles.title}>
            Welcome to <Link href="/">My Personal Web</Link>
          </h1>
          <button onClick={handleBtnScroll} style={{ visibility: scrollBtn, transition: ".2s" }} className={styles.btn_down}>
            <Arrow_Down></Arrow_Down>
          </button>
        </div>

        <div className={styles.personal_information}>
          <PersonalInformation></PersonalInformation>
        </div>

        <div className={styles.projects}>
          <Projects></Projects>
        </div>

        <div>
          <Skills></Skills>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
